# Special
foreground #e6deff
background #483f77
cursor #cabeff

# Colors
color0  #48454e
color1  #ffb4ab
color2  #c9c3dc
color3  #edb8cc
color4  #cabeff
color5  #605690
color6  #cabeff
color7  #e6e1e9

color8  #938f99
color9  #ffb4ab
color10 #c9c3dc
color11 #edb8cc
color12 #cabeff
color13 #605690
color14 #cabeff
color15 #c9c4d0